### ISSUE TITLE
Does u2f-api.js supports multi facets?

### ISSUE THREAD

**Issue by molekilla** [google/u2f-ref-code#112]
Hi

Does your API supports https://developers.yubico.com/U2F/App_ID.html ?
"
Multi-facet apps

If an app has many facets the AppID should be an HTTPS URL that resolves to a JSON list of facet IDs. For example:

https://example.com/app-id.json
…which could resolve to the following JSON content:

{
  "trustedFacets" : [{
    "version": { "major": 1, "minor" : 0 },
    "ids": [
        "https://login.example.com",
        "https://secure.example.com",
        "android:apk-key-hash:585215fd5153209a7e246f53286035838a0be227"
    ]
  }]
}
"
Thanks

**Comment by herrniemand** [comment]
@molekilla Yes. It does https://github.com/google/u2f-ref-code/blob/c4ced73224b4792cc927fc7683d85a6201d7cae9/u2f-chrome-extension/appid.js

**Comment by sree6494** [comment]
Hello, is the trusted facet validation supposed to be performed by ourselves, or how it is handled?

**Comment by cpiper** [comment]
Facet validation is performed by the browser

**Comment by sree6494** [comment]
I already have the FIDO server and client setup and is working fine. Now that I am trying to implement the Trusted Facets, I am confused on how the browser will get the trusted facets list and validate it with the origin url? - will it happen within the **u2f.sendSignRequest** javascript u2f API's? If so, what makes these u2f js APIs make a call to the app id provided in the trusted facets world, but not in the current scenario?

Any answers are highly appreciated!!!

**Comment by cpiper** [comment]
Yes, the appid provided in the u2f request should contain the URL of a json file. The browser will read that file and check to see if the requesting origin has permission to assert that appid.

If the origin of the request is the same as the appid origin, the browser doesn't bother checking the file and permits the request to continue.

**Comment by sree6494** [comment]
Cpiper, that clarifies a lot. Also, can you please provide any better resources about the major and minor specifications. I have gone thought the FIDO resources, and I didn't get much idea about it.
