### ISSUE TITLE
U2FTest.cc: test_Enroll should use the same application parameter before and after requesting user presence

### ISSUE THREAD

**Issue by reidrankin** [google/u2f-ref-code#128]
test_Enroll currently uses a random application parameter when triggering a user presence test, and a different random application parameter after the presence test is complete. Real applications use the same application parameter each time, and any implementation that attempts to verify that the user has approved the registration of a specific application parameter will fail under this test suite.

**Comment by prusnak** [comment]
Patch fixing this issue: https://github.com/trezor/trezor-mcu/files/1037858/u2ftest-trezor.txt
