### ISSUE TITLE
Why do we need to specify an extension

### ISSUE THREAD

**Issue by steowens** [google/u2f-ref-code#168]
Getting mixed messages from Google when I try to find out what the browser support is for u2f evidently it is built in as native part of chrome however the reference code seems to reference a Chrome extension do you or do you not have implementation support in Chrome without the extension?

**Comment by randallfox** [comment]
I think the extension is a mandatory built in extension.  It automatically comes with Chrome.  I think there are a few of these types of extensions in Chrome.  So, yes Chrome comes with U2F support built in, but the access patterns might be exactly like using an extension.    It works for me, and I never loaded an extension.

But don't take my word for it, download Chrome and try it without loading any extensions.  Also, u2f works in Firefox, provided you turn it on in the config settings.. (I'm admittedly more of a FireFox guy)

**Comment by Harry97** [comment]
@randallfox You're right.

> U2F has for a long time been supported in Chrome, although not with the standard window.u2f methods, but through a built-in extension. Nowadays, browsers seem to use window.u2f to expose the functionality.
[U2F-API](https://github.com/grantila/u2f-api)
