### ISSUE TITLE
Remote service using 2fa accessible by different protocols/domains

### ISSUE THREAD

**Issue by Polve** [google/u2f-ref-code#23]
I would like to develop a server side service making use of U2F, this service, exposing its API via REST calls and via websockets, will be accessible via different means: for example a web site, via a chrome/ff extension, and maybe via a custom mobile application.

In this scenario I'm unable to understand how do I need to set the URL parameter of the U2F request.

Since the goal is to have the same service accessed via different means, it should be natural for me to use the same U2F key when I login via web (using a public http server), or for example with a cordova-packaged app on my phone that is using localhost as a source for its files.

Does this means that I've to detect (i.e.: ask to the app) how it's accessing the API, and register several times the U2F device, for every different app I'm using to access the same service?

For example, a packaged app is accessed using localhost, but it connects the the remote server (the one that needs the 2fa) via websocket using a ws://domain.ext url.

Since using a remote service (that wants to use 2fa) via its API is now quite common, as it's common to develop javascript packaged applications running on the client, I suppose that there must be the "right" way to do it, but I've not yet understood which one, or even if it's possible at all.

**Comment by leshi** [comment]
Closing this issue as it's old and hasn't had any comments.  Feel free to re-open if it's still a question.

**Comment by Polve** [comment]
This question is still open for me. I understand that maybe it's more a documentation issue than a technical one, so feel free to point me to the right direction...
