### ISSUE TITLE
Multi-facet App ID not compatible with the standard

### ISSUE THREAD

**Issue by minisu** [google/u2f-ref-code#27]
Chrome 41 does not seem to support the [TrustedFacets structure](http://fidoalliance.org/specs/fido-u2f-v1.0-ps-20141009/fido-appid-and-facets-ps-20141009.html#trustedfacets-structure) that is declared by the specification.

Instead it supports the old, never standardized, way of listing facets which looks like this:

```
[
"https://accounts.google.com",
"https://myaccount.google.com",
"https://security.google.com"
]
```

This [causes confusion](http://stackoverflow.com/questions/28777759/u2f-multi-facet-appid-not-working-in-chromium-v40-x) for implementors of U2F.

**Comment by slisznia** [comment]
Thanks a lot for responding to my SO post.

**Comment by juanlang** [comment]
You're both correct. Sorry for the error. We're working to correct it ASAP.

**Comment by minisu** [comment]
Thanks @arnar! Will this be merged into Chromium or should I report a separate bug there?

**Comment by juanlang** [comment]
I just merged this into Chromium:
https://code.google.com/p/chromium/issues/detail?id=471522

It should be available in tonight's nightlies, and starting in Chrome 43.
