### ISSUE TITLE
u2f-ref-code documentation

### ISSUE THREAD

**Issue by doughri** [google/u2f-ref-code#29]
Hi Everyone,

I'm trying to modify the U2F ref code but I don't have enough knowledges in Java Web application development. I need a documentation, UML or description for all important classes in this project.
I've to implement this solution for a GWT Project.

Thank you,

**Comment by minisu** [comment]
Hi,

The Java u2f-ref-code here is an outdated (does not comply with the spec) example implementation (not a library).

I would recommend using [this library](https://github.com/Yubico/java-u2flib-server) instead. It aims to be a complete, up-to-date and well-documented library.

**Comment by doughri** [comment]
Hi, Mr.Minisu

Thank you for your help I'm trying to use this lib in my GWT project.
Could you please give a GWT simple project with U2F that can I use as reference to implement this solution in my side.

**Comment by minisu** [comment]
I have no experience with GWT, so you're on your own there. If you have any questions about the library that I linked to, please create an issue in that library's GitHub.

Let's let this be the last message in this thread, since we're getting off-topic.

**Comment by leshi** [comment]
@minisu in what way does this not comply with the spec?
