### ISSUE TITLE
Able to listen on domain other than localhost?

### ISSUE THREAD

**Issue by kynwu** [google/u2f-ref-code#50]
Found some places to modify the listening domain,
still don't work....

is this implementation able to achieve this requirement?

**Comment by leshi** [comment]
Yes, the hardcoded list of listening domains is here: https://github.com/google/u2f-ref-code/blob/f4265b14318094257df861364aeed50d5a376300/u2f-gae-demo/src/com/google/u2f/gaedemo/AppModule.java#L72. You can modify

Note that the built-in chrome support will not honor u2f requests from non-HTTPS sites.  You will need to start chrome with special flags and specifically tell chrome to allow http origins.  I submitted a pull request here: https://github.com/google/u2f-ref-code/pull/104 to explain the procedure.
