### ISSUE TITLE
https://u2fdemo.appspot.com/ stop working after last chrome update, version 46.0.2490.71 m

### ISSUE THREAD

**Issue by Kamalswami** [google/u2f-ref-code#56]
Demo website https://u2fdemo.appspot.com/ was working fine until Google Chrome Version 45 with Yubico Token. It stop working after last chrome update and that is 46.0.2490.71 m

Anybody has idea?

Thank you in advance...

**Comment by yankaiyu** [comment]
It still works on my macbook pro with OS X 10.10.5 and Chrome Version 46.0.2490.71 (64-bit). What is your environment and can you describe which part goes wrong more specifically?

**Comment by leshi** [comment]
Closing this issue. Please re-open if still the case.
